# Generated by Django 3.1.2 on 2020-10-28 07:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateGroupOfTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 10, 28, 10, 3, 42, 361672), verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='CreateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 10, 28, 10, 3, 42, 361672), verbose_name='date published')),
                ('whichGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toodooLogic.creategroupoftasks')),
            ],
        ),
        migrations.CreateModel(
            name='Createtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleTask', models.CharField(blank=True, max_length=40)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 10, 28, 10, 3, 42, 362671), verbose_name='date published')),
                ('whichList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toodooLogic.createlist')),
            ],
        ),
    ]
