# Generated by Django 3.1.2 on 2020-10-25 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateGroupOfTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='CreateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('whichGroup', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='toodooLogic.creategroupoftasks')),
            ],
        ),
        migrations.CreateModel(
            name='Createtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleTask', models.CharField(max_length=40)),
                ('whichList', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='toodooLogic.createlist')),
            ],
        ),
    ]
