# Generated by Django 3.1.2 on 2020-11-02 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodooLogic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creategroupoftasks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 8, 55, 41, 760508), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 8, 55, 41, 760508), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 8, 55, 41, 761502), verbose_name='date published'),
        ),
    ]
