# Generated by Django 3.1.2 on 2020-11-04 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodooLogic', '0002_auto_20201102_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtask',
            name='checked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creategroupoftasks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 10, 23, 5, 221358), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 10, 23, 5, 222383), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 10, 23, 5, 222383), verbose_name='date published'),
        ),
    ]
