# Generated by Django 3.1.2 on 2020-10-28 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toodooLogic', '0002_auto_20201028_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creategroupoftasks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 10, 35, 4, 351463), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 10, 35, 4, 352460), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createlist',
            name='whichGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toodooLogic.creategroupoftasks'),
        ),
        migrations.AlterField(
            model_name='createtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 10, 35, 4, 353458), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createtask',
            name='titleTask',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='createtask',
            name='whichList',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='toodooLogic.createlist'),
        ),
    ]
