# Generated by Django 3.1.2 on 2020-10-25 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodooLogic', '0003_auto_20201025_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creategroupoftasks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 22, 38, 7, 88827), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 22, 38, 7, 88827), verbose_name='date published'),
        ),
    ]
