# Generated by Django 3.1.2 on 2020-11-05 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodooLogic', '0003_auto_20201104_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createtask',
            name='checked',
        ),
        migrations.AlterField(
            model_name='creategroupoftasks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 20, 15, 46, 419712), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 20, 15, 46, 419712), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 20, 15, 46, 419712), verbose_name='date published'),
        ),
    ]
