# Generated by Django 3.1.2 on 2020-11-06 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodooLogic', '0005_auto_20201105_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtask',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creategroupoftasks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 23, 16, 39346), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 23, 16, 40344), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 23, 16, 40344), verbose_name='date published'),
        ),
    ]
