# Generated by Django 3.1.2 on 2020-11-06 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodooLogic', '0006_auto_20201106_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creategroupoftasks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 23, 18, 230892), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 23, 18, 231853), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 23, 18, 232885), verbose_name='date published'),
        ),
    ]
