# Generated by Django 3.1.2 on 2020-11-06 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodooLogic', '0007_auto_20201106_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createtask',
            name='complete',
        ),
        migrations.AlterField(
            model_name='creategroupoftasks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 32, 24, 542144), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 32, 24, 543141), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 32, 24, 543141), verbose_name='date published'),
        ),
    ]
